# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BusLocation' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BusLocation

pod 'CRToast'
pod 'Firebase/Core'
pod 'Firebase/AdMob'

end
